(() => {
  const root=document.getElementById("applications"),gate=document.getElementById("review-gate"),tabs=[...document.querySelectorAll(".review-tab")];
  let client,current="pending",applications=[];
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  function render(){const rows=applications.filter(item=>item.status===current);root.innerHTML=rows.length?rows.map(item=>`<article class="application-card"><div class="application-top"><div><h2>${esc(item.discord_name)}</h2><div class="application-meta">Submitted ${new Date(item.created_at).toLocaleString()}</div></div><span class="status-pill ${esc(item.status)}">${esc(item.status)}</span></div><div class="application-facts"><div><b>Time zone</b><span>${esc(item.timezone)}</span></div><div><b>Availability</b><span>${esc(item.availability)}</span></div><div><b>Experience</b><span>${esc(item.experience)}</span></div></div><div class="application-copy"><b>Motivation</b><p>${esc(item.motivation)}</p></div><div class="application-copy"><b>Bug report example</b><p>${esc(item.report_example)}</p></div><div class="application-actions"><button class="accept" data-id="${esc(item.user_id)}" data-status="accepted">Accept tester</button><button class="decline" data-id="${esc(item.user_id)}" data-status="declined">Decline</button></div></article>`).join(""):`<div class="empty-review">No ${esc(current)} applications.</div>`;}
  async function load(){client=window.RESPONDER_ROYALE_SUPABASE_CLIENT;if(!client){setTimeout(load,250);return;}const{data:{session}}=await client.auth.getSession();if(!session){gate.textContent="Sign in with the approved staff Discord account to review applications.";return;}const{data:reviewer}=await client.from("staff_reviewers").select("role").eq("user_id",session.user.id).maybeSingle();if(!reviewer){gate.textContent="This Discord account does not have staff review access.";return;}gate.textContent=`Secure staff access · ${reviewer.role}`;const{data,error}=await client.from("tester_applications").select("user_id,discord_name,timezone,availability,experience,motivation,report_example,status,created_at,updated_at").order("created_at",{ascending:false});if(error){gate.textContent=error.message;return;}applications=data||[];render();}
  tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(item=>item.classList.remove("active"));tab.classList.add("active");current=tab.dataset.status;render();}));
  root.addEventListener("click",async event=>{const button=event.target.closest("button[data-status]");if(!button)return;button.disabled=true;const status=button.dataset.status,{data:{session}}=await client.auth.getSession();const{error}=await client.from("tester_applications").update({status,reviewed_at:new Date().toISOString(),reviewed_by:session.user.id}).eq("user_id",button.dataset.id);if(error){gate.textContent=error.message;button.disabled=false;return;}const item=applications.find(row=>row.user_id===button.dataset.id);if(item)item.status=status;render();});
  window.addEventListener("load",load);
})();
