(() => {
  const cfg = window.RESPONDER_ROYALE_SUPABASE;
  const $ = (id) => document.getElementById(id);
  const headers = cfg ? { apikey: cfg.anonKey } : {};
  const get = async (path) => { const response = await fetch(`${cfg.url}/rest/v1/${path}`, { headers }); if (!response.ok) throw new Error("Unavailable"); return response.json(); };
  const empty = (element, copy) => { if (element) element.innerHTML = `<div class="empty-state">${copy}</div>`; };
  const ago = (value) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(value)) / 60000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago`; };
  async function loadVehicles() { const root = $("vehicle-carousel"); try { const rows = await get("public_vehicles?select=name,country,vehicle_type,rarity,emoji&order=updated_at.desc&limit=12"); if (!rows.length) return empty(root,"Vehicle previews will appear after the next bot sync."); root.replaceChildren(...rows.map(row=>{const card=document.createElement("article");card.className="vehicle-card";card.innerHTML='<div class="vehicle-emoji"></div><h4></h4><p></p><span class="rarity-chip"></span>';card.querySelector(".vehicle-emoji").textContent=row.emoji||"🚒";card.querySelector("h4").textContent=row.name;card.querySelector("p").textContent=`${row.country} · ${row.vehicle_type}`;card.querySelector(".rarity-chip").textContent=row.rarity;return card;})); } catch { empty(root,"Vehicle previews are temporarily unavailable."); } }
  async function loadLeaderboard() { const root=$("public-leaderboard"); try { const rows=await get("public_leaderboard?select=display_name,points,level,vehicles_collected&order=points.desc&limit=5"); if(!rows.length)return empty(root,"The first ranked collectors will appear here."); root.replaceChildren(...rows.map((row,index)=>{const item=document.createElement("div");item.className="leader-row";item.innerHTML='<i class="leader-rank"></i><div><b></b><span></span></div><strong class="leader-score"></strong>';item.querySelector("i").textContent=index+1;item.querySelector("b").textContent=row.display_name;item.querySelector("span").textContent=`Level ${row.level} · ${row.vehicles_collected} vehicles`;item.querySelector("strong").textContent=`${Number(row.points).toLocaleString()} pts`;return item;})); } catch { empty(root,"Leaderboard data is temporarily unavailable."); } }
  async function loadActivity() { const root=$("activity-feed"); try { const rows=await get("public_activity?select=title,description,created_at&order=created_at.desc&limit=6"); if(!rows.length)return empty(root,"Recent catches and events will appear here."); root.replaceChildren(...rows.map(row=>{const item=document.createElement("div");item.className="feed-item";item.innerHTML='<i class="feed-dot"></i><div><b></b><span></span></div><time></time>';item.querySelector("b").textContent=row.title;item.querySelector("span").textContent=row.description;item.querySelector("time").textContent=ago(row.created_at);return item;})); } catch { empty(root,"Recent activity will appear after the bot syncs it."); } }
  async function loadServers() { const root=$("server-showcase"); try { const rows=await get("public_servers?select=name,description,member_count&featured=eq.true&order=member_count.desc&limit=4"); if(!rows.length)return empty(root,"Featured communities are coming soon."); root.replaceChildren(...rows.map(row=>{const item=document.createElement("div");item.className="showcase-row";item.innerHTML='<div><b></b><span></span></div><strong class="leader-score"></strong>';item.querySelector("b").textContent=row.name;item.querySelector("span").textContent=row.description||"Responder Royale community";item.querySelector("strong").textContent=`${Number(row.member_count).toLocaleString()} members`;return item;})); } catch { empty(root,"Featured communities are coming soon."); } }
  document.querySelector(".mobile-toggle")?.addEventListener("click",()=>document.querySelector(".header nav")?.classList.toggle("open"));
  if(!cfg||cfg.anonKey.startsWith("PASTE_"))return; Promise.allSettled([loadVehicles(),loadLeaderboard(),loadActivity(),loadServers()]);
})();
